### ISSUE TITLE
this.videoWidth should be exposed

### ISSUE THREAD

**Issue by sethborg** [videojs/video.js#1901]
I used to be able to use the loadedmetadata event to change the video player width and height once the meta data was loaded but now this.videoWidth and this.videoHeight return undefined. It's been like this for the past few months worth of patches. not sure when it was broken

```html
<video id="video" width="300" height="200" preload="auto" controls="controls" autoplay="autoplay" class="video-js vjs-default-skin">
  <source src="video.mp4" type="video/mp4" >
</video>
```

```javascript
videojs('video', {}, function(){
	this.on('loadedmetadata', function() {
console.log(this.videoWidth);  // test with a 720x480 video for example
//document.getElementById('video').style.width = this.videoWidth + 'px';
//document.getElementById('video').style.height = this.videoHeight + 'px';
	});
});
```

Edits by @mmcc: Code fences

**Comment by heff** [comment]
Can you say which browser you're using and any plugins?

You could help us by creating [a jsbin](http://jsbin.com/axedog/edit?html,js,output) for your script there so we can verify it quickly. And then the next steps we would take here is to determine if anything changed with the video tag itself in the specific browser you're testing in.

**Comment by mmcc** [comment]
Was `videoHeight` ever actually a thing? There are [`height()` and `width()`](https://github.com/videojs/video.js/blob/2c14c70ee80e7baa9dcd494d965423d6bccc93c7/src/js/component.js#L897-L929) methods, but even all the way back to 4.1 it looks like [all](https://github.com/videojs/video.js/blob/4e5c28cc561487ff29394d19dce3a420675e4f9d/test/unit/api.js#L41-L42) the [references](https://github.com/videojs/video.js/blob/7bcb1d218c764d4d2729af0bfd589e1b62158b58/src/js/player.js#L1744-L1745) are commented out (although, oddly enough, we are still [exporting them](https://github.com/videojs/video.js/blob/4e5c28cc561487ff29394d19dce3a420675e4f9d/src/js/player.externs.js#L46-L47).

So anyway, I'm not sure what version you were using, but afaik, those methods have never been available in 4.0.0.

**Comment by sethborg** [comment]
width() and height() do not return the actual video's dimensions. What I'm doing here is setting the wrong dimensions beforehand and then resizing once the actual video's dimensions are received from the meta data.

It must have been before 4.0.0 then but it used to be a thing because this used to work. And it should be a thing now. What's the point of a loadedmetadata event if you can't use the metadata?

I'm on Windows 7. I'm using Firefox 36. I tried Chrome 40 and IE 11. It's not a browser issue.

**Comment by mmcc** [comment]
I absolutely, 100% agree that this should be implemented, I'm just nearly positive that it [never was](https://github.com/videojs/video.js/blob/3.2.3/src/player.js#L838-L839) (that's 3.2.2, the last 3.x release). Perhaps you were querying the actual html5 tech for the information? You could still do that, it just wouldn't work for Flash.

**Comment by sethborg** [comment]
I tested back to 4.3 and couldn't find one that worked but I swear I was doing it at one point but perhaps you're right.

While you're in there, what other metadata is accessible that isn't exposed?

**Comment by mmcc** [comment]
[This list](https://github.com/videojs/video.js/blob/4e5c28cc561487ff29394d19dce3a420675e4f9d/test/unit/api.js#L34-L42) should about sum it up.

**Comment by sethborg** [comment]
Maybe this will spur someone to add these features. I tried adding:

vjs.Html5.prototype.videoWidth = function(){ return this.el_.videoWidth; };
vjs.Html5.prototype.videoHeight = function(){ return this.el_.videoHeight; };

vjs.Flash.prototype['videoWidth'] = function(time){
  return this.el_.vjs_getProperty('videoWidth');
};

vjs.Flash.prototype['videoHeight'] = function(time){
  return this.el_.vjs_getProperty('videoHeight');
};

but it didn't work so I'm using:

videojs('video', {}, function(){
	this.on('loadedmetadata', function() {
		if ($('#video_flash_api').length) {
			$('#video').css({
				width: $('#video_flash_api').get(0).vjs_getProperty('videoWidth'),
				height: $('#video_flash_api').get(0).vjs_getProperty('videoHeight')
			});
		}
		else {
			$('#video').css({
				width: document.getElementById('video_html5_api').videoWidth,
				height: document.getElementById('video_html5_api').videoHeight
			});
		}
	});
});

**Comment by heff** [comment]
This will make it into 5.0 with #1952. @sethborg I'd be interested to get your feedback on that one.

**Comment by sethborg** [comment]
I found my code that exposed this.videoWidth inside $('#video').on('loadedmetadata', function() {}

It seems to have something to do with using jquery and setting:

var v=$('<video id="datbox_video" preload="auto" controls="controls" autoplay="autoplay" class="video-js vjs-default-skin" style="display:none;"><source id="datbox_source" src="'+$(el).attr('href')+'" type="video/mp4" /></video>');

Any idea why this works? Source code (datbox.js) http://sethb.org/datbox/

**Comment by heff** [comment]
Closing this because I believe it was fixed by #1952. Correct me if you find otherwise.

@sethborg I think that probably works because it's adding the event listener directly to the video element instead of the player.

**Comment by ayyash** [comment]
I don't understand, I followed all the related tickets, I just downloaded the latest version, but I still don't see how to read the metadata videoWidth? any pointers?

**Comment by ayyash** [comment]
Oh, I think i get it now 
```
videojs('video', {}, function(){
    this.on('loadedmetadata', function() {
       console.log(document.getElementById("video").videoWidth);
    });
});
```

**Comment by vaninv** [comment]
```
videojs('video', {}, function(){
    this.on('loadedmetadata', function() {
       console.log(this.videoWidth());
    });
});
```
Can also do the trick
