### ISSUE TITLE
Requirejs with videojs

### ISSUE THREAD

**Issue by mimse** [videojs/video.js#2724]
Hi,

I'm trying to use videojs 5 with requirejs / almond but running is to this problem

![screen shot 2015-10-22 at 09 56 25](https://cloud.githubusercontent.com/assets/1250254/10659872/641d6b60-78a3-11e5-9ae2-c6298d5db029.png)

I'm I doing something wrong, or is it a bug?

**Comment by gkatsev** [comment]
We're using browserify to built a standalone build that should theoretically support it. However, you're using bower and I think we're exporting the wrong file to bower right now. See #2740.

**Comment by gkatsev** [comment]
I believe this is fixed.

**Comment by MatheusMoura17** [comment]
hi @gkatsev, the problem is still persisting. I using videojs v6.8.0 and requirejs v2.3.2

![](http://i68.tinypic.com/2r6h7jn.jpg)

**Comment by gkatsev** [comment]
@MatheusMoura17 can you please open a new issue with a reduced test case? Thanks.

**Comment by mafar** [comment]
It is currently working with requirejs 

to fix this, please read my answer https://github.com/videojs/video.js/issues/5680#issuecomment-570120497

I think **Documentation** should be **updated !!!**
