### ISSUE TITLE
flv stopped working... recently we started getting an error of CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED

### ISSUE THREAD

**Issue by born2net** [videojs/video.js#3537]
## Description

Started getting an error of

```
video.dev.js:1384 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported. vjs.MediaError {code: 4, message: "The video could not be loaded, either because the …rk failed or because the format is not supported."}
```
### Expected

Not to get an error and have it play flv format
### Actual

```
video.dev.js:1384 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported. vjs.MediaError {code: 4, message: "The video could not be loaded, either because the …rk failed or because the format is not supported."}
```

 I am wondering if any changes were made on videojs to stop the critical support of flash video?

regards

Sean

**Comment by mister-ben** [comment]
Which version were you using when it worked and which version are you using now?

**Comment by born2net** [comment]
Hi, was and still using local version of: 
vjs.CDN_VERSION = '4.6';

**Comment by misteroneill** [comment]
If you're using a local copy, it wouldn't have changed unless you changed it. Are you using a SWF loaded from the CDN, perhaps? If so, what's the URL it's getting the SWF from? Did you change your `techOrder` to remove Flash?

**Comment by born2net** [comment]
ya I know... but still something broke, maybe google made changes to Chrome?
and still same in source 

```
vjs.options = {
  // Default order of fallback technology
  'techOrder': ['html5','flash'],
  // techOrder: ['flash','html5'],
  ...
```

regards

**Comment by gkatsev** [comment]
Chrome has been steadily making things bad for flash over the last year or two. If your playing is smaller than about 400x600, it might have issues.

**Comment by born2net** [comment]
this is the error:

![ca](https://cloud.githubusercontent.com/assets/5090936/17711618/596839bc-63a7-11e6-92a2-026204a80708.PNG)

**Comment by born2net** [comment]
ya it is a small screen

**Comment by gkatsev** [comment]
That's probably it. chrome won't load flash if the area is too small.

**Comment by born2net** [comment]
I tried to increase the size 1000px x 1000px but same issue...

**Comment by born2net** [comment]
![cap2](https://cloud.githubusercontent.com/assets/5090936/17711787/0977d5a6-63a8-11e6-81c3-f1953f5c1e2a.PNG)

**Comment by gkatsev** [comment]
So, I believe we fixed this issue in videojs-flash via videojs/videojs-flash#39.

**Comment by cAstraea** [comment]
Can someone help with a working example implementing this please. Been trying to make it work but still getting the same error.
