### ISSUE TITLE
errors when using webpack

### ISSUE THREAD

**Issue by liuhaoliang** [videojs/video.js#5432]
When using npm build the react source, then run the dist code,console "Uncaught ReferenceError: t is not defined"

version: 7.1.0
environment:react 
buid :webpack

<img width="817" alt="2018-09-12 9 51 52" src="https://user-images.githubusercontent.com/16020037/45397198-8690db00-b671-11e8-8e6e-ba1a48f64d7e.png">

**Comment by liuhaoliang** [comment]
fixed the issue in 7.2.2

**Comment by gkatsev** [comment]
Has to do with some `typeof` rules that get mangled in uglify2, which we finally got around.

**Comment by waqar-baig** [comment]
I am still getting this error in my angular 6 project when I "ng build --prod"
works with development mode.
Please help

**Comment by ntourne** [comment]
I got this same error when running `ng build` with default "production" configuration.

* Angular v9.1.9
* Video.js 7.0.3
