### ISSUE TITLE
Video playback constantly stops/pauses on iOS devices.

### ISSUE THREAD

**Issue by Robbcode** [videojs/video.js#6330]
## Description
Video playback of MP4 x264/aac file will stop/pause playback shortly after started, if manually unpaused playback will stop again shortly afterwards.

Stop/Pause can happen as quickly as 14 seconds in to playback. 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Load page on iOS with videojs and mp4 x264/aac video.
2. Press to start playback on iOS device.

### Expected
Video playback of MP4 file should be uninterrupted. 

### Actual
Video playback of MP4 stops/pauses repeatedly. 

### Error output
Browser console shows no errors.

## Additional Information

I have reproduced the problem on Firefox desktop v70 and setting user agent string to iOS.

what version of videojs does this occur with?

videojs v7.7.0 - v7.7.1

The problem does not seem to happen on version before theses.

browsers / OSes

iPhone/iPad.
iPhone; CPU iPhone OS 12_4_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1

Firefox desktop v70.0 with user agent changed to same as above seem to reproduce the problem as well.

### plugins
No plugins

**Comment by gkatsev** [comment]
Do you have the file that you're having issues with? Locally, I do not have any issues with mp4 files with h264 and aac codecs in them. It's likely that you need to re-transcode your file.

**Comment by woniuzfb** [comment]
+1 same issue here using it for HLS no such issue before

**Comment by woniuzfb** [comment]
> Do you have the file that you're having issues with? Locally, I do not have any issues with mp4 files with h264 and aac codecs in them. It's likely that you need to re-transcode your file.

[HLS constantly pauses](http://hbo.epub.fun)

**Comment by DispatchCommit** [comment]
What tech are you using for your player? Are you overriding the native player for any (all?) browsers? Does changing the overrideNative value fix the issue?

```javascript
// Create video.js player
this.player = videojs('streamplayer', {
  // ...
  html5: {
    hls: {
      overrideNative: !videojs.browser.IS_SAFARI,
      // ...
    },
  },
});
```

**Comment by woniuzfb** [comment]
> Are you overriding the native player for any (all?) browsers? Does changing the overrideNative value fix the issue?

overrideNative: true
No.It didn't fix the issue.
Chrome/Safari/all browsers on ios happens

**Comment by asoulliereHT** [comment]
reverting to 7.6.6 resolved this issue for now.

with 7.7.1, overrideNative didn't help
`'nativeAudioTracks': false,
'nativeVideoTracks': false,
'hls': {
   'overrideNative': true
}`

**Comment by aaronsoulliere** [comment]
reverting to 7.6.6 resolved this issue for now.

with 7.7.1, overrideNative didn't help
'nativeAudioTracks': false, 'nativeVideoTracks': false, 'hls': { 'overrideNative': true }

**Comment by aaronsoulliere** [comment]
reverting to 7.6.6 resolved this issue for now.

with 7.7.1, overrideNative didn't help
`'nativeAudioTracks': false, 'nativeVideoTracks': false, 'hls': { 'overrideNative': true }`

**Comment by jb-alvarado** [comment]
Same problem here with hls live stream, 7.6.6 works, but not 7.7.1 except Firefox.

**Comment by mrbatista** [comment]
Same problem with hls live stream.

**Comment by samueleastdev** [comment]
Same problem constantly pausing on IOS, ill set up a demo.

**Comment by samueleastdev** [comment]
Can also confirm the issue is not present on 7.6.6.

**Comment by gkatsev** [comment]
A demo would be great. Is there a specific iOS version and device combination that this happens on? I've not been able to reproduce locally. If someone who has it reliably able to go through the commits via git bisect (https://github.com/videojs/video.js/compare/v7.6.6...v7.7.1) that would be highly appreciated.

**Comment by hlibmykhailov** [comment]
> A demo would be great. Is there a specific iOS version and device combination that this happens on? I've not been able to reproduce locally. If someone who has it reliably able to go through the commits via git bisect ([v7.6.6...v7.7.1](https://github.com/videojs/video.js/compare/v7.6.6...v7.7.1)) that would be highly appreciated.

Have same problems on any iOS device only on versions above 7.6.6 _/\-_-/\_
On 7.6.6 works well.

**Comment by jb-alvarado** [comment]
Here is a demo:
https://srs2.ad-europa.org/demo/
Tested devices are iPhone 5, iPhone 8 and iPhone 10 (X)

**Comment by supermoos** [comment]
Seeing the same issue on iPad Pro, iOS 13.2

**Comment by mister-ben** [comment]
@jb-alvarado thank you for the reproducible example. It's vastly more useful than all the "same issue" comments.

Safari seems confused about the DVR window with this video. It starts showing about -26:40:45 but changes to -59:43 after it freezes. There may be an issue with the stream itself but it's likely that c791cd8c4ea7675688882d39d745096f817e1395 is the cause of the pause in reaction to that.

Your video is live HLS. No idea if that's representative of all the reports here. The first description mentions MP4 so not necessarily the same problem. Don't know if the others were live, some mention HLS.

**Comment by jb-alvarado** [comment]
I have here now also a demo with an mp4 file. By it stops to, after two minutes.

**Comment by gkatsev** [comment]
While we investigate, I've set `latest` on npm to 7.6.6.

**Comment by gkatsev** [comment]
Oh, I guess it's still latest. We'll make sure that this is resolved before a 7.7 release branch is promoted to latest.

**Comment by gkatsev** [comment]
By the way, I've reproduced this and I'm looking into it. Not exactly sure why I couldn't reproduce before.

**Comment by gkatsev** [comment]
I'm releasing Video.js 7.7.4 which reverts the previous change. If you haven't downgraded yet, consider trying this version out.

**Comment by gkatsev** [comment]
It's up as `next` on npm and I also published it on our CDN https://vjs.zencdn.net/7.7.4/video.js (or video.min.js)

**Comment by gburgwardt** [comment]
FWIW with 7.7.4 I'm still seeing this bug, regardless of overridenative setting, with an hls live stream
