### ISSUE TITLE
7.9.x results in readonly error on Samsung TV

### ISSUE THREAD

**Issue by JeppeTh** [videojs/video.js#6921]
## Description
I can't create videojs player on Samsung TV from version 7.9.0. I get an exception saying 
"TypeError: Attempted to assign to readonly property."
I don't know how to get the callstack

7.8.4 works fine.

## Steps to reproduce

    var div = document.createElement('video-js');
    div.id = 'video-player';
    div.style.width = MAX_WIDTH + 'px';
    div.style.height = MAX_HEIGHT + 'px';
    div.style.top = '0px';
    div.style.left = '0px';
    div.style.position = 'absolute';
    document.getElementById('video-container').appendChild(div);

    videojs('video-player');

## Results
"TypeError: Attempted to assign to readonly property." exception

### Error output
"TypeError: Attempted to assign to readonly property." exception

#### videojs
7.9.x
#### browsers
Samsung
#### OSes
Samsung Tizen 2.3

**Comment by gkatsev** [comment]
Hey, is this still an issue with Video.js 7.10.2 (latest) or even 7.11 (currently in pre-release)

**Comment by JeppeTh** [comment]
Just tried 7.11 and still same issue.

**Comment by JeppeTh** [comment]
I ran in debug mode, removed my catch and used v7.11 videojs.js
I then got some more info - seems it complains about line 3234
    _proto.set = function set(key, value) {
      this.set_[key] = value; // line 3234
      return this;
    };

**Comment by gkatsev** [comment]
@JeppeTh that's incredibly helpful. I think this was actually something that just got fixed in #7000.

**Comment by JeppeTh** [comment]
Haha - yes seem very likely. I can confirm after fix is part of a release.

**Comment by JeppeTh** [comment]
Problem solved! 👍 
Using a 7.9.x version didn't solve the issues I have with some HLS streams though ;-)
