### ISSUE TITLE
If the video is scaled, the position of the progress bar drag is not accurate！

### ISSUE THREAD

**Issue by pxim** [videojs/video.js#6922]
## Description
If the video is scaled, the position of the progress bar drag is not accurate

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. scale the videojs div.

### Expected
Please describe what you expected to see.
normal
![1](https://user-images.githubusercontent.com/5111701/97852180-5fa23100-1d31-11eb-812f-1e9e458aadc9.gif)

abnormal
![2](https://user-images.githubusercontent.com/5111701/97853318-e99ec980-1d32-11eb-9ebf-4d88f8252a56.gif)

The default style of the video tag will not show this problem.
![3](https://user-images.githubusercontent.com/5111701/97860554-47d0aa00-1d3d-11eb-84da-b71c40112a10.gif)

### Actual
Please describe what actually happened.
the position of the progress bar drag is not accurate

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
v7
#### browsers
what browser are affected?
chrome
#### OSes
what platforms (operating systems and devices) are affected?
win10
### plugins
are any videojs plugins being used on the page? If so, please list them below.
no

**Comment by gkatsev** [comment]
Hey, which version of Video.js is being used? We just fixed this in 7.9.4 and newer.

**Comment by pxim** [comment]
The original version 7.8.1 was used, but now it is updated to version 7.10.1. This problem does not appear on the PC side, 
but it will still appear in the mobile terminal (ios 13.4.1 chrome 73.0.3683.68)

**Comment by pxim** [comment]
> Hey, which version of Video.js is being used? We just fixed this in 7.9.4 and newer.

The original version 7.8.1 was used, but now it is updated to version 7.10.1. This problem does not appear on the PC side,
but it will still appear in the mobile terminal (ios 13.4.1 chrome 73.0.3683.68)

demo: http://bmw.jingge.com/hongyan/mobile/
![image](https://user-images.githubusercontent.com/5111701/97935772-83f32180-1db4-11eb-857a-9c66ceb4304f.png)

**Comment by gkatsev** [comment]
Yeah, unfortunately mobile doesn't really provide the same information that desktop does. It's likely possible to fix but requires a lot more work and isn't as straight forward.

**Comment by pxim** [comment]
> Yeah, unfortunately mobile doesn't really provide the same information that desktop does. It's likely possible to fix but requires a lot more work and isn't as straight forward.

OK，thank you.
