### ISSUE TITLE
video append of xxxxxxb failed for segment #0 in playlist 0-placeholder-uri-0

### ISSUE THREAD

**Issue by onurdumangoz** [videojs/video.js#7587]
Hello everyone. Happy new year to all of you.
I got error on the title; video append of xxxxxxb failed for segment #0 in playlist 0-placeholder-uri-0

I render an episode of anime.

Render code:
```
ffmpeg -hide_banner -i OP_0001.mkv -map_metadata -1 ^
-vf "scale=-2:720" ^
-keyint_min 72 -g 72 ^
-c:v libsvtav1 -c:a libopus -qp 30 ^
-pix_fmt yuv420p ^
-movflags frag_keyframe+empty_moov ^
OP_0001_720.mp4
```
I also render for 1080p.

I'm using [Shaka Packager](https://github.com/google/shaka-packager) (v2.6.1-634af65-release) for DASH:
```
packager ^
in=OP_0001_720.mp4,stream=audio,output=OP_0001_dash_audio.mp4 ^
in=OP_0001_720.mp4,stream=video,output=OP_0001_dash_720p.mp4 ^
in=OP_0001_1080.mp4,stream=video,output=OP_0001_dash_1080p.mp4 ^
--mpd_output OP_0001.mpd
```

#### videojs
7.18.0
#### browsers
Chrome 96.0.4664.110
#### OSes
Windows 10 - 21H2 (build 19044.1415)
### plugins
videojs-http-source-selector
videojs-contrib-quality-levels.min

**Comment by vlad909** [comment]
@onurdumangoz hello!
the problem is solved?

**Comment by venomone** [comment]
Still existing with 7.20.3 ...
Really I don't understand this, we now have this bug about opened 3 times:

https://github.com/videojs/video.js/issues/7008 -> This thread
https://github.com/videojs/video.js/issues/7587
https://github.com/videojs/video.js/issues/7841

And I could also open a 4th issue onto that. To me, it seems that we often see new features, but old bugs keep persisting.
I can't use VideoJS for HLS streaming in production, simply because each time I switch the quality, no matter on what device, I frequently drop into video append error until I restart the browser, clean the cache, then it's magically working again, and damn it sucks, can we please have this append issue on priority 1 super ultra critical as it's basically totally interrupting the playback experience ...
