### ISSUE TITLE
Failed to read the 'handle' property from 'MediaSource': MediaSourceHandle creation is currently supported only in a dedicated worker.

### ISSUE THREAD

**Issue by locpd** [videojs/video.js#7905]
After updating Chrome to version 105.0.5195.54 (Official Build) (64-bit), video.js stop working with this error:

`Uncaught DOMException: Failed to read the 'handle' property from 'MediaSource': MediaSourceHandle creation is currently supported only in a dedicated worker.`

Video.js version: 7.9
Here's the url of the player: https://xemphim.vip/test

**Comment by icmaia90** [comment]
@locpd are you still experiencing this error?

**Comment by jessefalzone** [comment]
We're on v7.5.5 and still experiencing the issue.  I'll see if the latest works.

Possibly due to this change that shipped in Chrome 105: https://chromestatus.com/feature/5177263249162240

**Comment by locpd** [comment]
> @locpd are you still experiencing this error?

I upgraded to 7.20.2 and it works now.

**Comment by dalecurtis** [comment]
This is tracked by https://bugs.chromium.org/p/chromium/issues/detail?id=1358542 -- Video.js devs, is there a version after which you recommend folks upgrade to? I haven't been able to track down exactly where this ended up fixed.

**Comment by gkatsev** [comment]
7.20.2 is a good one. contrib-hls has been deprecated since ~2018. 7.5.5 is itself a 3-year-old version of Video.js.
If I were to guess, I would assume that 7.10 would be the oldest version of Video.js where this is fixed.

**Comment by rlcruzsu** [comment]
Hi all, after updating VideoJS version to 7.20.2 yesterday, it worked. But now it seems like the issue is happening again even on 7.20.2, is this the same for others on 7.20.2? Thanks.

**Comment by jgreen01su** [comment]
Hi All. My team and I upgraded our Video.js version to 7.20.2 yesterday and it worked, but today the issue came back.

Today, we found that chrome version _105.0.5195.52_ is effected by this issue while the latest version _105.0.5195.102_ isn't. What's weird is I'm sure we tested version _105.0.5195.52_ yesterday and it was working.

Anyway, I decided to install the **chrome beta version _106.0.5249.21_** and found this issue is effecting it. This makes me worried that this issue may come back in a future chrome update.

Does anyone know what is causing this issue in chrome? Is there a universal fix?

**Comment by gkatsev** [comment]
I do not see any issues with 7.20.2 via https://videojs-preview.netlify.app/sandbox/hls.html or https://videojs-http-streaming.netlify.app/ on `105.0.5195.102`. I also tried out the beta version (`106.0.5249.21`) and it's working for me there as well.

**Comment by dalecurtis** [comment]
105.*.102 disables mse+workers so is fixed. 106/107+ haven't been patched yet. I expect 106 to disable mse+workers with the next release, but we'll likely leave 107 in a broken state (while it's in dev/beta) until an appropriate fix for mse+workers is found (so additional breakages can be detected). If no fix is found by stable release we'll disable MSE+workers there.

**Comment by jgreen01su** [comment]
@gkatsev Thank you! Just found that the quick in-place update we made yesterday on our server reverted somehow. Now we're doing a proper deployment.

7.20.2 does fix the issue on Chrome Beta. Sorry for the confusion.

**Comment by gkatsev** [comment]
No worries, it happens. Glad you figured it out.

Also, confirmed that 7.10.x is the first working version.
https://v7-10-2--videojs-docs.netlify.app/test-example/ works
but https://v7-9-0--videojs-docs.netlify.app/test-example/ doesn't
You'll need to do `player.src('https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8')` in dev tools on there to verify.

**Comment by wolenetz** [comment]
MSE-in-Workers launch in Chrome has been reverted from Chrome 107 now. I'm working on relanding with fix in 108. Follow along on https://crbug.com/878133.

**Comment by gkatsev** [comment]
Thanks for the update @wolenetz!
